from django.conf.urls import include, url
from . import views
handler404 = 'views.my_404_view'
urlpatterns = [
	    url(r'^$',views.index,name='index'),
        url(r'^score/$',views.score_list,name='score_list'),
        url(r'^score/(?P<student_id>[0-9]+)/$',views.score_details,name='score_details'),
        url(r'^instructor_page/$',views.instructor_page,name='instructor_page'),
        url(r'^challenges/$',views.challenge_details,name='challenge_details'),
        url(r'^about/$',views.about,name='about'),
        url(r'^contact/$',views.contact,name='contact'),
        url(r'^demo0/$',views.demo0,name='demo0'),
        url(r'^demo1/$',views.demo1,name='demo1'),
        url(r'^demo2/$',views.demo2,name='demo2'),
        url(r'^demo3/$',views.demo3,name='demo3'),
        url(r'^demo4/$',views.demo4,name='demo4'),
        url(r'^demo5/$',views.demo5,name='demo5'),
        url(r'^demo5/donotlookinhere/password.txt$',views.demo5_1,name='demo5_1'),
        url(r'^crypto/$',views.crypto,name='crypto'),
        url(r'^app_logic0/$',views.app_logic0,name='app_logic0'),
        url(r'^app_logic1/$',views.app_logic1,name='app_logic1'),
        url(r'^ido/0/$',views.ido0,name='ido0'),
        url(r'^ido/1/$',views.ido1,name='ido1'),
        url(r'^ido/1/editUser/1/$',views.ido1_userEdit1,name='ido1_userEdit1'),
        url(r'^ido/1/editUser/2/$',views.ido1_userEdit2,name='ido1_userEdit2'),
        url(r'^ido/1/editUser/3/$',views.ido1_userEdit3,name='ido1_userEdit3'),
        url(r'^xss/1/$',views.xss_1,name='xss_1'),
        url(r'^rand_form/$',views.rand_form,name='rand_form'),
        url(r'^rand_form0/$',views.rand_form0,name='rand_form0'),
        url(r'^vuln_form/$',views.vuln_form,name='vuln_form'),
]
