# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbl', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='level',
            old_name='score',
            new_name='value',
        ),
        migrations.AddField(
            model_name='score',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbl.Level'),
        ),
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbl.Student'),
        ),
    ]
