# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pbl', '0003_auto_20160129_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remark', models.CharField(max_length=100, null=True)),
                ('challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbl.Challenge')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='remark',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=datetime.datetime(2016, 1, 31, 18, 17, 4, 196546, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbl.Level'),
        ),
        migrations.AddField(
            model_name='competition',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbl.Student'),
        ),
    ]
