# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbl', '0005_auto_20160131_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
