# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbl', '0006_competition_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='challenge_id',
            new_name='challenge',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='level_id',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='student_id',
            new_name='student',
        ),
    ]
