# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 02:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbl', '0007_auto_20160201_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
